### PR TITLE
Changes for improved docker build

### PR DESCRIPTION
**Pull request by brosenberg42**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-projects/4)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-projects/4)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[.dockerignore, line 27 at r1](https://reviewable.io/reviews/openmpf/openmpf-projects/4#-LyVnsXN-2ZkneeH8HhF:-LyVnsXO8KWDxiUK81sH:b-55dphh) ([raw file](https://github.com/openmpf/openmpf-projects/blob/66f33a5b4480496cdf26d3ef2f312349e5d3497f/.dockerignore#L27)):*
> ```ignore
> #############################################################################
> 
> **/target
> ```

Some of these files should not be generated in the openmpf-projects TLD, right? I would assume that it would be better to add those entries to the submodule .dockerignore files.

Did you add the entries to prevent git from telling you that changes were made to the submodules due to these files? 
___
*[.dockerignore, line 35 at r1](https://reviewable.io/reviews/openmpf/openmpf-projects/4#-LyVnkH21d6ldsL_RhHr:-LyVnkH3C4hnu9YK7_Me:bjtbv77) ([raw file](https://github.com/openmpf/openmpf-projects/blob/66f33a5b4480496cdf26d3ef2f312349e5d3497f/.dockerignore#L35)):*
> ```ignore
> **/openmpf/trunk/install
> 
> openmpf-components
> ```

Why do you want to ignore changes to these submodules?

**Review by jrobble — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-projects/4)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

___
*[.dockerignore, line 27 at r1](https://reviewable.io/reviews/openmpf/openmpf-projects/4#-LyVnsXN-2ZkneeH8HhF:-LyVpLiaDvaADjLPz_yM:bo6r1sj) ([raw file](https://github.com/openmpf/openmpf-projects/blob/66f33a5b4480496cdf26d3ef2f312349e5d3497f/.dockerignore#L27)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Some of these files should not be generated in the openmpf-projects TLD, right? I would assume that it would be better to add those entries to the submodule .dockerignore files.

Did you add the entries to prevent git from telling you that changes were made to the submodules due to these files? 
</blockquote></details>

Sorry, I'm confusing this file with .gitignore. Nevermind.

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-projects/4)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

___
*[.dockerignore, line 35 at r1](https://reviewable.io/reviews/openmpf/openmpf-projects/4#-LyVnkH21d6ldsL_RhHr:-LyVpaxy6HLA_L4glmyT:b9e6xo5) ([raw file](https://github.com/openmpf/openmpf-projects/blob/66f33a5b4480496cdf26d3ef2f312349e5d3497f/.dockerignore#L35)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Why do you want to ignore changes to these submodules?
</blockquote></details>

Nevermind.

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-projects/4)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

___
*[.dockerignore, line 33 at r1](https://reviewable.io/reviews/openmpf/openmpf-projects/4#-LyVqAtR1tfT3YhftRNw:-LyVqAtS7c86GTXn-ZoP:b-rgj6qm) ([raw file](https://github.com/openmpf/openmpf-projects/blob/66f33a5b4480496cdf26d3ef2f312349e5d3497f/.dockerignore#L33)):*
> ```ignore
> **/build
> **/*.iml
> **/openmpf/trunk/install
> ```

Should we also be ignoring .dockerignore?

**Review by jrobble — COMMENTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-projects/4)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-projects/4)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @jrobble)

___
*[.dockerignore, line 33 at r1](https://reviewable.io/reviews/openmpf/openmpf-projects/4#-LyVqAtR1tfT3YhftRNw:-LyYz1aA7ubkdteOOFo3:b-896fix) ([raw file](https://github.com/openmpf/openmpf-projects/blob/66f33a5b4480496cdf26d3ef2f312349e5d3497f/.dockerignore#L33)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Should we also be ignoring .dockerignore?
</blockquote></details>

Done.

**Review by jrobble — APPROVED** [review]
I didn't verify the SHAs, but `.dockerignore` looks fine.

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-projects/4#-:-M0xb4Kk-21Uk6iXEko4:b8tcfls)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request closed without merging**
